bids-standard/bids-validator

.github/workflows/deno_tests.yml

`macos-12` has been turned off. I don't think we need to pin these. If we do, we should add a comment, so that next time we'll know why it's like this.

chore(ci): Use latest OSs

---

src/files/deno.ts
src/files/dwi.test.ts
src/files/dwi.ts

Fixes #9, adds a test that fails thus (if we revert the second commit):
```
Test bval/bvec parsing ... Load 3 bvals - missing newline => ./src/files/dwi.test.ts:10:11
error: AssertionError: Values are not equal.
[Diff] Actual / Expected
[
[
"0",
"1",
"2",
-       "",
],
]
throw new AssertionError(message);
^
at assertEquals (https://jsr.io/@std/assert/1.0.7/equals.ts:51:9)
at file:///home/chris/Projects/bids/validator/src/files/dwi.test.ts:12:5
at innerWrapped (ext:cli/40_test.js:191:11)
at exitSanitizer (ext:cli/40_test.js:107:33)
at Object.outerWrapped [as fn] (ext:cli/40_test.js:134:20)
at TestContext.step (ext:cli/40_test.js:492:37)
at file:///home/chris/Projects/bids/validator/src/files/dwi.test.ts:10:11
Test bval/bvec parsing ... Load 3 bvals - missing newline => …
```

fix(bval): Handle trailing whitespace without newlines

---

docs/index.md
docs/validation-model/context.md
docs/validation-model/index.md
docs/validation-model/inheritance-principle.md

This PR adds discussion of the validation model, intended to be along the lines of the "Explanations" quadrant of [diataxis](diataxis.fr).
I would be interested in feedback on whether this is understandable. I move back and forth between Python for algorithm, typescript for type definition and YAML for data description. They feel natural to me, but I've been up to the eyeballs in this stuff.
@yarikoptic @bendhouseart Could I trouble you for reviews?
**Rendered docs**: https://bids-validator--94.org.readthedocs.build/en/94/validation-model/index.html

doc: Document the validation model, context and inheritance principle

---

.github/workflows/web_build.yml

This builds two copies of the validator:
* Whatever we're releasing (tag or triggered build) as https://bids-standard.github.io/bids-validator/
* `main` as https://bids-standard.github.io/bids-validator/dev/
Closes #86.

feat: Publish main along with release under bids-validator/dev

---

.github/CONTRIBUTING.md
.github/workflows/deno_tests.yml
deno.json

Replacing the short-lived `stable`/`main` duo with `main`/`dev`. Docs to hopefully make things clear.

chore/doc: Revert main to stable schema, update docs to explain branching

---

.github/workflows/deno_tests.yml

Pretty simple. Just includes a `jq` sanity check to make sure the tag matches the `deno.json` field.
We could build on this in the future to push regular dev builds.

chore(ci): Publish to JSR on tag

---

.github/workflows/web_build.yml

Get old https://bids-standard.github.io/bids-validator/legacy/ links working again.

fix: Restore legacy/ subdirectory, redirecting to legacy-validator

---

src/files/browser.ts
src/files/deno.ts
src/files/filetree.test.ts
src/files/filetree.ts

Currently, the Deno CLI reads the bidsignore file and then loads the filetree. The premature load isn't necessary because `FileTree`s now can hold a reference to the `FileIgnoreRules` object.
The web UI loads the `FileTree` without passing them a reference to the `FileIgnoreRules` object, and then loads the bidsignore after the fact. So this has the possibility of missing ignores that https://github.com/bids-standard/legacy-validator/pull/2152 was intended to address.
Finally, the `pathsToTree` function doesn't allow any ignoring at all, which limits our ability to write tests.
This PR allows `filesToTree` to accept a `FileIgnoreRules` object and inject it in every `FileTree` it creates. Then we can make the web/CLI implementations work the same: build the tree, load the bidsignore. The …

rf(filetree): Uniformize bidsignore reading between web, CLI and test functions

---

src/tests/regression.test.ts

test: Check that bidsignored files are accepted in scans.tsv

---

.github/CONTRIBUTING.md
changelog.d/20241114_165444_effigies.md
changelog.d/20241114_192344_effigies_scriv.md
changelog.d/scriv.ini

This PR adopts and configures [scriv](https://scriv.readthedocs.io/en/latest/) for changelog management. I also added a changelog entry for #113.
While I'm at it, I added some guidance to CONTRIBUTING which will help guide people in the use of conventional commits, prefixed branches and scriv categories.
I may have gone on too long about style commits/PRs... Edits welcome.
Closes #105.

doc: Adopt scriv as a changelog manager

---

deno.json

The schema is effectively stable, in that it's a pain to change it significantly. We're recognizing that by releasing the latest BIDS 1.10.0 schema patch as schema-1.0.0. I will make a corresponding bump to have `dev` track schema-1.1.0-dev.

chore: Bump @bids/schema v1.0.0

---

src/files/deno.test.ts
src/files/deno.ts
src/files/ignore.ts
src/main.ts
src/setup/options.ts
src/tests/regression.test.ts

This is an optimization to allow for raw datasets with extensive nested derivatives to be efficiently validated. It does not change the default behavior or performance characteristics.
This proactively prunes the filetree during construction, which can prevent many unnecessary stats and construction of many unnecessary objects. The primary downside is that this prevents recursive validation and including pruned files in the dataset size estimate.
Closes #115.

feat: Add --prune option to prevent walking subtrees

---

README.md

Without providing a schema path, bst defaults to another installed schema instead of my modifies one:
```
2024-11-22 15:40:41,436 [    INFO] No schema path specified, defaulting to the bundled schema, `/home/tstoeter/.local/lib/python3.11/site-packages/bidsschematools/data/schema`.
```
Making the schema path explicit fixes this.

Fix bst call for compiling schema

---

README.md
docs/index.md

#120 did not quite do the job. This brings the README section copied from docs/index.md into line with its source, and updates index.md with the suggestion to add (BIDS) to the BIDS link.

doc: Conform README and docs/index

---

src/schema/expressionLanguage.test.ts
src/schema/expressionLanguage.ts
src/tests/schema-expression-language.test.ts

This updates the `intersects()` function in the schema expression language to:
1) Return the intersection, if non-empty. The order will match the order in the longer list.
2) Return `null` on empty intersections to ensure that `intersects()` remains falsey.
This seems like the simplest resolution for resolving bids-standard/bids-specification#914 along the lines of:
> If `participants.tsv` exists, then the `participant_label` entries are a superset of subject directories and participant labels found in `phenotype/`.
With this change, the rule could be written:
```yaml
SubDirSubset:
selectors:
- path == '/participants.tsv'
checks:
- |
allequal(
sorted(intersects(dataset.subjects.participant_id, dataset.subjects.sub_dirs)),
sorted(dataset.subjects.sub_dirs)
)
PhenotypeSubset:
selectors:
- …
```

feat(expr): Make intersects() return the intersection when non-empty

---

README.md
docs/user_guide/command-line.md

Without that run which asks to save results into external file would fail with
error: Uncaught (in promise) PermissionDenied: Requires write access to "derivatives/bids-validator/deno-bids-validator.txt", specify the required permissions during compilation using `deno compile --allow-write`
at writeFileSync (ext:deno_fs/30_fs.js:899:3)
at Object.writeTextFileSync (ext:deno_fs/30_fs.js:962:10)
at main (https://jsr.io/@bids/validator/2.0.1/src/main.ts:38:12)
at eventLoopTick (ext:core/01_core.js:175:7)
at async https://jsr.io/@bids/validator/2.0.1/src/bids-validator.ts:2:16
- There is also `--allow-run` which I do not know if should be enabled or not -- e.g. do you run HED validator as external tool, or anything else?
- Is it possible to identify such needs at compile time?

Add -W (--allow-write) to deno build instructions

---

src/schema/context.ts
src/validators/hed.ts

@rwblair  In looking at `hed.js` it looks as though the `hedSchemas` object is being reloaded for every file being validated. Since the HED schema version specification is the same for an entire BIDS dataset, it need only be loaded once.
@happy5214 (FYI)

Updated the hed validation to only load schemas once

---

src/validators/hed.ts

sty: Address deno lint comments for validators/hed.ts

---

changelog.d/20250214_094554_markiewicz_load_subjects.md
src/schema/context.ts

Type checker doesn't like it, but this fixes the failure to load from TSV files for now. We don't want to synchronously load TSV files during object construction, but nor do we really want to treat subjects as maybe missing.
The real fix I think will be to only call the function once, so we can get rid of the `null` check.

fix: Load subjects

---

CHANGELOG.md

Failed to consistently use `scriv` this last release.

doc: Update changelog for 2.0.2

---

changelog.d/20250216_174252_dominik.welke_fix_warn_message.md
src/issues/list.ts

PR to update the warning and error message.
please have a look if this is alright @effigies 
closes #161

fix misleading warning/error message

---

src/files/browser.ts
src/files/deno.ts
src/files/nifti.ts
src/files/tiff.ts
src/schema/fixtures.test.ts
src/types/filetree.ts

Deno 2.2 via TypeScript 5.7 made typed arrays generic. Specifying the generic for Uint8Array and DataView resolves failures seen in #166.
@effigies I think this is the better alternative to #167.

fix: Correct Uint8Array / DataView usage for TypeScript 5.7

---

deno.json

While debugging #170 I realized I wasn't seeing all errors because the test runner was pointed at just the tests directory.

fix: Run all test files with `deno task test`

---

src/validators/json.ts

Some datasets on OpenNeuro are having JSON output contaminated by this output from AJV's internal logging:
```
strict mode: missing type "array" for keyword "maxItems" at "#/properties/ScreenResolution/anyOf/0/items" (strictTypes)
strict mode: missing type "array" for keyword "minItems" at "#/properties/ScreenResolution/anyOf/0/items" (strictTypes)
strict mode: missing type "array" for keyword "maxItems" at "#/properties/ScreenSize/anyOf/0/items" (strictTypes)
strict mode: missing type "array" for keyword "minItems" at "#/properties/ScreenSize/anyOf/0/items" (strictTypes)
```
Examples include ds005810 and ds005811.

fix: Prevent AJV logs from contaminating output

---

deno.json
deno.lock

Holding off on `@std/assert`, since that breaks some equality checks.
Builds on #167 to ensure type checking passes.

chore: Bump @bids/schema v1.0.3 and other dependencies

---

deno.json
deno.lock
src/files/browser.test.ts
src/types/filetree.ts

Follow-up to #168, addressing some changes in deep equality checking introduced in https://github.com/denoland/std/pull/6153. Now the values of `BIDSFile.stream` and `BIDSFile.ignore` are compared, while we were previously only checking structure. Adding a stream that is an identical object resolves the first, and the second requires ensuring `.ignore` does not crash on dataset roots and passing an expected `BIDSIgnore` to files in the expected tree.

chore: Bump @std/assert >= 1.0.8

---

.github/workflows/wheels.yml
README.md
pdm_build.py
pyproject.toml

#181 is a bit dissatisfying in that it requires a deno compile step, followed by a python packaging step. While this works for `python -m build --wheel`, it fails for `uv build --wheel`, which attempts to create an sdist and then build the wheel from it. Additionally, it would be nice for `python -m build` and `uv build` to just work.
I was curious to see if you could build an sdist with typescript sources, and pdm required essentially no configuration to achieve that. Compiling the binary and dumping it somewhere that pdm could find to package took some more working out, but turned out not to be too hard. With that, we can publish both sdist and wheel, and users with working `deno` installations can build their own, if our wheels don't cover them.
This uses …

chore: Compile Deno validator and package in wheels for PyPI

---

src/schema/context.ts
src/schema/walk.test.ts
src/schema/walk.ts
src/summary/summary.ts
src/types/schema.ts
src/validators/filenameIdentify.test.ts
src/validators/filenameIdentify.ts
src/validators/internal/emptyFile.ts

feat: Validate directories, do not recurse into schema-declared opaque dirs

---

.github/workflows/deno_tests.yml
deno.json
deno.lock
src/issues/list.ts
src/validators/hed.ts

This new version of hed-validator (not yet released) changes the API significantly. This is an early preview of the changes. Tests do not pass with the current release, and they were not attempted with the development branch.

Rewrite HED code for version 4.0.0 of hed-validator

---

changelog.d/20250411_093755_rosswilsonblair_191_update_exit_code.md
src/bids-validator.ts

Exit code of 2 on `--help` seems to be coming from cliffy, leaving as is with the assumption no one is relying on the exit code from the help output for anything. fixes #191

use exit code 16 on exit with validation errors per bids apps spec

---

pdm_build.py
web/deno.lock

Looks like we get typescript 5.6 in Windows and 5.7 elsewhere. I don't know what the causes are, but it doesn't seem particularly worth fighting, since types get checked elsewhere, and there shouldn't be a change in generated code.

chore(build): Skip type checking when compiling wheels

---

changelog.d/20250509_080014_markiewicz_bad_sidecars.md
src/schema/applyRules.ts

In #202, `dataset_description.json` and `README.md` were being checked for sidecar fields `Description` because of a rule that applies to all derivatives. However, these files cannot have sidecars, so we need a way to detect them.
The `readEntities()` function tags `README.md` with a suffix of "README", and `dataset_description.json` with a suffix of `description`, along with their extensions, but, when we run filenameIdentify, we clean the context of components that don't apply to any rules:
https://github.com/bids-standard/bids-validator/blob/d80712956b07f4346b26952e5580cd3ff3bf37b8/src/validators/filenameIdentify.ts#L221-L237
Therefore `dataset_description.json` loses its suffix and extension, which is why sidecar checking wasn't disabled. `README.md`, or any other text file, were …

fix: Skip sidecar checks for text files

---

deno.json
deno.lock

IIUC, `<package>@~<version>` permits patch upgrades but not minor upgrades, which I think is what we want for the schema.
Lock file updated.

chore: Update BIDS schema, relax to ~version

---

deno.json
deno.lock

@happy5214 Since merging #220, the validator has been hanging and failing to exit. Running on any bids-example should demonstrate it:
```
$ deno run -A src/bids-validator.ts --ignoreWarnings tests/data/bids-examples/synthetic
```
Downgrading `hed-validator` (other changes did not need to be reverted) resolves it.

fix: Revert to HED validator 4.0

---

changelog.d/20250825_075606_markiewicz_dataset_types.md
src/issues/list.ts
src/setup/options.test.ts
src/setup/options.ts
src/tests/regression.test.ts
src/validators/bids.test.ts
src/validators/bids.ts

Closes #229. I went with a pass-list so that we can say `datasetTypes: ['raw', 'derivative']` in OpenNeuro without waiting on `'study'` to be a valid value to disallow it.

feat: Add DatasetType passlist to allow applications to limit support

---

.github/workflows/docker-build-push.yml
Dockerfile
changelog.d/20250826_074930_markiewicz_docker.md

This PR reenables DockerHub pushes. This request has come up enough times that I suppose it's worth doing.
Using alpine to slim down the container as much as possible. It's still 150MB or so locally, but that's better than 220.
No attempt is made to do multi-architecture builds. Will open an issue.

chore: Reenable DockerHub pushes

---

changelog.d/20250828_104256_markiewicz_tsv_gz.md
src/files/tsv.test.ts
src/files/tsv.ts
src/issues/list.ts
src/schema/context.ts
src/schema/tables.ts

~~Partially addresses #239 by loading data for validation. I think we need #234 in before I start debugging validation itself, since that reworks it so significantly.~~
Closes #239. This currently only generates a warning, but that's because all non-required columns emit warnings instead of errors. I would like to change them to errors, but that's a separate PR.

 feat: Enable type checking on tsv.gz files

---

changelog.d/20250828_161028_markiewicz_deprecate_89plus.md
src/issues/list.ts
src/schema/tables.test.ts
src/schema/tables.ts

This allows 89+ to be used in age columns, regardless of whether we start raising errors for optional columns.

feat: Split out deprecation warning for age=="89+"

---

changelog.d/20250828_163229_markiewicz_tsv_type_errors.md
src/issues/list.ts
src/schema/tables.test.ts
src/schema/tables.ts

Following #234, it is always possible to define a type precisely in a sidecar definition. It is therefore safe to error when types don't match, because the solution is "Improve the type of your column."
Builds on #240

feat: Always error on incorrect TSV types

---

src/schema/tables.test.ts
src/schema/tables.ts

Accidentally stopped validating index columns at all in #243. Updated tests to catch it by using `ColumnsMap`, which does not work with `x in columns`.

fix: Check index columns

---

changelog.d/20250911_171112_markiewicz_file_access_errors.md
src/files/access.test.ts
src/files/access.ts
src/files/gzip.test.ts
src/files/gzip.ts
src/files/json.test.ts
src/files/json.ts
src/files/nifti.test.ts
src/files/nifti.ts
src/files/tiff.test.ts
src/files/tiff.ts
src/files/tsv.test.ts
src/files/tsv.ts
src/schema/associations.ts
tests/data/broken-symlink

This PR creates `src/files/access.ts` that provides functional access to a bytestream, bytes and Unicode text. These wrap the properties and methods on `BIDSFile` and translate any IO errors into `FILE_READ` issues.
This seemed cleaner than injecting issue concepts into the `BIDSFile` model, and hopefully avoids complicating the process of adding a `BIDSFileRemote` or similar.
Closes #252

feat: Add file access functions that translate errors into issues

---

changelog.d/20250915_144507_markiewicz_cache_json.md
src/files/json.test.ts
src/files/json.ts
src/schema/walk.ts

Because loading associated file sidecars is going to be necessary for #260, it makes sense to start caching JSON loads.

feat: Cache JSON file loads

---

changelog.d/20250916_102738_rosswilsonblair_data_url_encoding_issue_174.md
web/src/App.tsx

- Add encodeURIComponent to JSON.stringify in data URL
- Include charset=utf-8 for proper character encoding
- Fixes issue #174 where special characters in JSON output caused broken download links

fix: properly encode JSON data in data URL for download link

---

changelog.d/20250916_123856_rosswilsonblair_error_on_non_utf8_tsv.md
src/files/streams.ts
src/files/tsv.test.ts
src/files/tsv.ts
tests/data/iso8859.tsv

Added a `fatal` argument to `createUTF8Stream`. `createUTF8Stream` is used by the Deno BidsFile implementation's `text` function, so I didn't hard code `{fatal: true}` at decoder creation like is done for json files.
fixes #43

throw utf8 encoding error for tsv files, add non utf-8 test data and test.

---

changelog.d/20250918_173356_yarikoptic_enh_crash.md
src/setup/loadSchema.ts

I think current behavior violates the principle of the least surprise: I ran validation while providing custom schema source, it executed with many warnings and errors reported to the screen. It is only after scrolling far up, I saw that actually my specification was wrong and operation resorted to built-in schema.
Moreover, having varying results depending on network flukes is also not a good behavior.
TODOs (if agreed in principle)

Throw an error, do not just log an error, if provided schema is not legit

---

.github/workflows/deno_tests.yml
changelog.d/20250917_113053_markiewicz_message_interpolation.md
src/schema/applyRules.test.ts
src/schema/applyRules.ts
src/schema/expressionLanguage.test.ts
src/schema/expressionLanguage.ts

This PR adds issue message formatting, to allow for schema issue messages that reference context variables to provide more useful messages.
This builds on the expression evaluation utility to achieve a limited subset of Python's `str.format` functionality. The conversion is very simple: `{` becomes `${`, backslashes are escaped, and finally backticks are escaped so that we can use Javascript's interpolation strings.
While doing this, it seemed cleanest to move encapsulation into `expressionLanguage.ts`, and prepare the context (by setting the expression language functions and wrapping in a `Proxy`) just once in each exported function for `applyRules.ts`. Internally, `applyRules.ts` assumes that it has a prepared context object.

feat: Add issue message formatting
